version: '3.8'
services:
  semantle:
    image: semantle
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: semantle
      POSTGRES_PORT: 5432